### PR TITLE
Improve the setup process.

### PR DESCRIPTION
**Pull request by dzwarg**
Update the setup.py process to automatically build the scala assembly.
The setup process checks for the existance of 'sbt', and runs the sbt
'clean' and 'assembly' commands during `build`.

Setup also copies the built jar file into the system classpath during
`install`, so that no classpath environment needs to be set.

Install a `register` command to register the package with pypi via a
locally-mapped file: `.pypirc`, written at build time with pypi creds.

### CODE REVIEW

**Comment by dzwarg** [comment]
@twneale Ready for your review.

**Comment by twneale** [comment]
This is a mammoth contribution, and a huge improvement. Thank you!

I tested out the setup.py install ("pip install --egg ." on this branch, for the record) and the jar copy did error out due to lack of permissions, so what I'm wondering @dzwarg is whether there's a way to make "pip install py4jdbc" accept flags or additional commands when invoked so that: 1) if the jar file needs to be built it gets built, and perhaps deposited at a location specified by a CLI arg, and 2) if the user wants it copied to the system class path, perhaps they pass another flag for that? 

For the default case, it's probably best to skip building the assembly jar, the typical use case being when we're running a scheduled job on jenkins and we pull a pre-built assembly jar from HDFS (including many other driver jars) to achieve a speedup. Automatically building the jar in that scenario would prolong the job quite a bit and we wouldn't even end up using the auto-built jar. 

Thoughts? I think py4j follows a similar approach and leaves people on their own as far as building the jar. Their circle CI config builds it on the fly before running the tests, but setup.py expects people to separately build it. 

Thank you again @dzwarg for this mighty overhaul.

**Comment by twneale** [comment]
Also, I was just double-checking python 2.7 type annotations, and they work but they have to be placed in comments. I'd be open to just removing all the annotations in the interests of 2.7 compatibility, which is a much bigger benefit if my view. At some future (possibly boozy) juncture we can always try to revive the annotations as comments.

**Comment by dzwarg** [comment]
@twneale Can you take a look at these command line argument changes? I added:

- `--with-jar`: as an argument to `build`: True/False; as an argument to `install`: "system" or a file path where the jar should be installed.

If `system` is specified, it assumes root privileges. This is consistent with the way other installations work (`install` will try to install into site-packages, which require root/sudo permissions, too).

**Comment by twneale** [comment]
@dzwarg This is awesome, totally awesome. I'm sending you a small pull request on your branch and I think it'll be ready.

**Pull request merged**
